#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

[[ $# -gt 0 ]] || {
    echo "usage: [bootstrap2_hostname=<hostname>] $0 components/<component> [...]" 
    exit 1
}

mmdebstrap_args=(--mode=unshare)

components=(components/0?-* "$@" components/9?-*)

for component in "${components[@]}"
do
    [[ -d "${component}" ]] || {
        echo "EE: component ${component} is not a directory"
        exit 1
    }
    [[ -f "${component}/args" ]] && mapfile -t -O ${#mmdebstrap_args[@]} mmdebstrap_args < "${component}/args"
    [[ -d "${component}/hooks" ]] && mmdebstrap_args+=(--hook-directory="${component}/hooks")
done

mmdebstrap_args+=(bullseye -)

# needs to be in the environment for copy-out of /boot
export bootstrap2_target_dir="out-$(date +%Y%m%d-%H%M%S)"
mkdir "$bootstrap2_target_dir"

{
    echo   "II: running mmdebstrap"
    echo   "II: with components:"
    printf "II:   %s\n" "${components[@]}"
    echo   "II: and args:"
    printf "II:   %s\n" "${mmdebstrap_args[@]}"
} | tee "${bootstrap2_target_dir}/run.txt"

mmdebstrap "${mmdebstrap_args[@]}" \
| tar2sqfs --compressor zstd --comp-extra level=1 --block-size 1M "${bootstrap2_target_dir}/filesystem.squashfs"
