#!/bin/bash
set -euo pipefail
shopt -s nullglob
IFS=$'\n\t'

[[ $# -gt 0 ]] || {
    echo "usage: [bootstrap2_hostname=<hostname>] $0 [--no-defaults] components/<component> [...]"
    exit 1
}

mmdebstrap_args=(--mode=unshare)

if [[ "$1" == "--no-defaults" ]]
then
    shift
    components=("$@")
else
    components=(components/0?-* "$@" components/9?-*)
fi

for component in "${components[@]}"
do
    [[ -d "${component}" ]] || {
        echo "EE: component ${component} is not a directory"
        exit 1
    }
    [[ -f "${component}/args" ]] && mapfile -t -O ${#mmdebstrap_args[@]} mmdebstrap_args < "${component}/args"
    [[ -d "${component}/hooks" ]] && mmdebstrap_args+=(--hook-directory="${component}/hooks")
    for packages in "${component}"/*.packages
    do
        mmdebstrap_args+=(--include="$(perl -pe 'y/ /=/; y/\n/ /' $packages)")
    done
    [[ -f "${component}/mirror" ]] && mirror="$(cat "${component}/mirror")"
done

mmdebstrap_args+=(bullseye -)
[[ "${mirror:-}" ]] && mmdebstrap_args+=("$mirror")

bootstrap2_target_dir="/tmp/bootstrap2-out-$(date +%Y%m%d-%H%M%S)"
mkdir "$bootstrap2_target_dir"
mkdir "$bootstrap2_target_dir/live"

{
    echo   "II: running mmdebstrap"
    echo   "II: with components:"
    printf "II:   %s\n" "${components[@]}"
    echo   "II: and args:"
    printf "II:   %s\n" "${mmdebstrap_args[@]}"
} | tee "${bootstrap2_target_dir}/run.txt"

mmdebstrap "${mmdebstrap_args[@]}" \
| tar2sqfs --compressor zstd --comp-extra level=1 --block-size 1M "${bootstrap2_target_dir}/live/filesystem.squashfs"
rdsquashfs -u boot -p "${bootstrap2_target_dir}/boot" "${bootstrap2_target_dir}/live/filesystem.squashfs"
